"""empty message

Revision ID: 13252890e8d8
Revises: 
Create Date: 2021-11-06 11:44:02.166945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13252890e8d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_first_name'), 'contacts', ['first_name'], unique=False)
    op.create_index(op.f('ix_contacts_last_name'), 'contacts', ['last_name'], unique=False)
    op.create_index(op.f('ix_contacts_message'), 'contacts', ['message'], unique=False)
    op.create_table('rampagents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('user_code', sa.String(length=60), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rampagents_email'), 'rampagents', ['email'], unique=True)
    op.create_index(op.f('ix_rampagents_first_name'), 'rampagents', ['first_name'], unique=False)
    op.create_index(op.f('ix_rampagents_last_name'), 'rampagents', ['last_name'], unique=False)
    op.create_index(op.f('ix_rampagents_user_code'), 'rampagents', ['user_code'], unique=True)
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=True),
    sa.Column('departure', sa.String(length=20), nullable=True),
    sa.Column('destination', sa.String(length=20), nullable=True),
    sa.Column('aircraft_registration', sa.String(length=20), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('rampagent_id', sa.Integer(), nullable=True),
    sa.Column('flight_loadsheet', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['rampagent_id'], ['rampagents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_aircraft_registration'), 'flights', ['aircraft_registration'], unique=False)
    op.create_index(op.f('ix_flights_date'), 'flights', ['date'], unique=False)
    op.create_index(op.f('ix_flights_departure'), 'flights', ['departure'], unique=False)
    op.create_index(op.f('ix_flights_destination'), 'flights', ['destination'], unique=False)
    op.create_index(op.f('ix_flights_flight_loadsheet'), 'flights', ['flight_loadsheet'], unique=False)
    op.create_index(op.f('ix_flights_flight_number'), 'flights', ['flight_number'], unique=True)
    op.create_table('processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_name', sa.String(length=60), nullable=True),
    sa.Column('start_time', sa.String(length=60), nullable=True),
    sa.Column('end_time', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=True),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('rampagent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['rampagent_id'], ['rampagents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processes_end_time'), 'processes', ['end_time'], unique=False)
    op.create_index(op.f('ix_processes_process_name'), 'processes', ['process_name'], unique=False)
    op.create_index(op.f('ix_processes_start_time'), 'processes', ['start_time'], unique=False)
    op.create_index(op.f('ix_processes_status'), 'processes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processes_status'), table_name='processes')
    op.drop_index(op.f('ix_processes_start_time'), table_name='processes')
    op.drop_index(op.f('ix_processes_process_name'), table_name='processes')
    op.drop_index(op.f('ix_processes_end_time'), table_name='processes')
    op.drop_table('processes')
    op.drop_index(op.f('ix_flights_flight_number'), table_name='flights')
    op.drop_index(op.f('ix_flights_flight_loadsheet'), table_name='flights')
    op.drop_index(op.f('ix_flights_destination'), table_name='flights')
    op.drop_index(op.f('ix_flights_departure'), table_name='flights')
    op.drop_index(op.f('ix_flights_date'), table_name='flights')
    op.drop_index(op.f('ix_flights_aircraft_registration'), table_name='flights')
    op.drop_table('flights')
    op.drop_index(op.f('ix_rampagents_user_code'), table_name='rampagents')
    op.drop_index(op.f('ix_rampagents_last_name'), table_name='rampagents')
    op.drop_index(op.f('ix_rampagents_first_name'), table_name='rampagents')
    op.drop_index(op.f('ix_rampagents_email'), table_name='rampagents')
    op.drop_table('rampagents')
    op.drop_index(op.f('ix_contacts_message'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_last_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_first_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
