"""empty message

Revision ID: 53f9805e3b57
Revises: ba2be64fcfda
Create Date: 2021-10-17 14:06:38.895790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f9805e3b57'
down_revision = 'ba2be64fcfda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('date', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_flights_date'), 'flights', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flights_date'), table_name='flights')
    op.drop_column('flights', 'date')
    # ### end Alembic commands ###
