"""empty message

Revision ID: 76d7922dcf4c
Revises: 49f9cf9a56a0
Create Date: 2021-10-24 12:58:54.853568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76d7922dcf4c'
down_revision = '49f9cf9a56a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pics',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('rendered_data', mysql.TEXT(), nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('pic_date', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
