"""empty message

Revision ID: 7af4a439bbbe
Revises: 9d24ad919256
Create Date: 2021-10-12 17:41:50.064499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af4a439bbbe'
down_revision = '9d24ad919256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('rampagent', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'flights', 'rampagents', ['rampagent'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_column('flights', 'rampagent')
    # ### end Alembic commands ###
