"""empty message

Revision ID: 7b1c080f50ef
Revises: 95c64d727fd2
Create Date: 2021-10-09 15:37:38.523884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1c080f50ef'
down_revision = '95c64d727fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=True),
    sa.Column('departure', sa.String(length=20), nullable=True),
    sa.Column('destination', sa.String(length=20), nullable=True),
    sa.Column('aircraft_registration', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_aircraft_registration'), 'flights', ['aircraft_registration'], unique=False)
    op.create_index(op.f('ix_flights_departure'), 'flights', ['departure'], unique=True)
    op.create_index(op.f('ix_flights_destination'), 'flights', ['destination'], unique=False)
    op.create_index(op.f('ix_flights_flight_number'), 'flights', ['flight_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flights_flight_number'), table_name='flights')
    op.drop_index(op.f('ix_flights_destination'), table_name='flights')
    op.drop_index(op.f('ix_flights_departure'), table_name='flights')
    op.drop_index(op.f('ix_flights_aircraft_registration'), table_name='flights')
    op.drop_table('flights')
    # ### end Alembic commands ###
