"""empty message

Revision ID: c55d9ae478ad
Revises: 7333d3464682
Create Date: 2021-10-12 19:31:38.295160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55d9ae478ad'
down_revision = '7333d3464682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_name', sa.String(length=60), nullable=True),
    sa.Column('start_time', sa.String(length=60), nullable=True),
    sa.Column('end_time', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=True),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('rampagent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['rampagent_id'], ['rampagents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processes_end_time'), 'processes', ['end_time'], unique=False)
    op.create_index(op.f('ix_processes_process_name'), 'processes', ['process_name'], unique=False)
    op.create_index(op.f('ix_processes_start_time'), 'processes', ['start_time'], unique=False)
    op.create_index(op.f('ix_processes_status'), 'processes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processes_status'), table_name='processes')
    op.drop_index(op.f('ix_processes_start_time'), table_name='processes')
    op.drop_index(op.f('ix_processes_process_name'), table_name='processes')
    op.drop_index(op.f('ix_processes_end_time'), table_name='processes')
    op.drop_table('processes')
    # ### end Alembic commands ###
