"""empty message

Revision ID: cc71e59d8726
Revises: 76d7922dcf4c
Create Date: 2021-10-24 15:47:59.529756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc71e59d8726'
down_revision = '76d7922dcf4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('flight_loadsheet', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_flights_flight_loadsheet'), 'flights', ['flight_loadsheet'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flights_flight_loadsheet'), table_name='flights')
    op.drop_column('flights', 'flight_loadsheet')
    # ### end Alembic commands ###
